name: Selenium UI Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Build and test
        run: |
          # Build
          mvn clean install -DskipTests
          # Run tests with headless mode enabled via config
          mvn test -Dsurefire.suiteXmlFiles=testng.xml
        working-directory: ./selenium_java_ui_auto
